# Generated by Django 5.2.10 on 2026-01-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='devise',
            field=models.CharField(choices=[('XOF', 'F XOF'), ('EUR', 'EUR'), ('USD', 'USD')], default='XOF', max_length=3),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
