# Generated by Django 5.2.10 on 2026-01-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imageprofil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
