# Generated by Django 5.2.10 on 2026-01-26 16:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='imageprofil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imageprofil'),
        ),
    ]
