# Generated by Django 5.2.10 on 2026-01-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_first_name_remove_user_last_name'),
        ('accounts', '0004_remove_first_name_last_name'),
    ]

    operations = [
    ]
